### ISSUE TITLE
Duplication of nextXXX and XXX in ZnBufferedReadStream

### ISSUE THREAD

**Issue by hogoww** [svenvc/zinc#113]
Currently ZnBufferedReadStream uses both nextInt32 and int32 that express the same behavior.
Maybe one could(/should?) be deprecated?
I'd tend to keep nextInt32.
Might need some API cleanup for consistency too.

What do you think @svenvc ?
(I could do it, just thought I'd ask first)

**Comment by svenvc** [comment]
Yes, you are right and I agree: it would be better if this duplication did not exist.

However, it exists in ZnBufferedReadStream because it exists in PositionableStream.

If you want to fix this, I suggest you start changing all users (there aren't that many in the image, but there might be many more in external packages) and add a deprecation in Pharo Alpha (11).

Zinc itself might only follow slowly because it wants to remain compatible with older Pharo versions (currently from Pharo 7 upwards).

I would move this issue to Pharo itself and see what others think.

**Comment by hogoww** [comment]
Will do, thank you ! :)
