### ISSUE TITLE
ZnClient queryAddAll: keyedCollection should add not put

### ISSUE THREAD

**Issue by jmari** [svenvc/zinc#19]
I think this method should use queryAt: add: instead of queryAt: put: in order to include duplicate keys.

queryAddAll: keyedCollection
	"Add all key -> value elements of keyedCollection 
	as an HTTP query parameters to the current request."

	keyedCollection keysAndValuesDo: [ :key :value |
		self queryAt: key **add**: value ]

**Comment by svenvc** [comment]
Yes you are right, that would be consistent with ZnUrl>>#queryAddAll:

**Comment by svenvc** [comment]
Name: Zinc-HTTP-SvenVanCaekenberghe.467
Author: SvenVanCaekenberghe
Time: 6 October 2017, 1:49:36.648938 pm
UUID: fab90d2c-4117-0d00-b2b8-97690478619a
Ancestors: Zinc-HTTP-SvenVanCaekenberghe.466

Change ZnClient>>#queryAddAll: to use #queryAt:add: instead of #queryAt:put: so that is consistent with ZnUrl>>#queryAddAll: (thx jmari)

**Comment by svenvc** [comment]
Thx

I just did another sync from the MC repos: commit e9ad944e067cdfe5a69d3d94562c53cc274eff5b

**Comment by jmari** [comment]
Thanks to you for this great framework!
