### ISSUE TITLE
Using ZnMimePart in Pharo 7.0 throws a "Instance of ZnCharacterStream did not understand #binary"

### ISSUE THREAD

**Issue by ioanaverebi** [svenvc/zinc#23]
I am performing a request against the Confluence REST API. This request should upload a file using multipart content type. I get the following error when performing the request (this is Pharo 7.0)
<img width="960" alt="screen shot 2018-09-26 at 23 08 57" src="https://user-images.githubusercontent.com/2392264/46108744-6c193e80-c1e7-11e8-8491-5a80afd0ccbc.png">

The code is the following:
`uploadFileFrom: filePath inSpaceWithContentID: contentID
	| part pathSegments |
	pathSegments := { 'wiki'. 'rest'. 'api'. contentID. 'child'. 'attachment' }.

	part := ZnMimePart fieldName: 'file' fileNamed: filePath .
	part headers contentType: ZnMimeType default.
	part.

	ZnClient new
		url: (url asZnUrl addPathSegments: pathSegments yourself);
		username: username password: password;
		headerAt: 'X-Atlassian-Token' put: 'no-check';
		addPart: part;
		post;
		response.`

Any suggestions what the issue might be?

**Comment by svenvc** [comment]
Yes this was reported before and I already had a look and a fix, but I got stuck somewhere else. I will try to have another look tomorrow.

**Comment by svenvc** [comment]
Hi,

This should now be fixed in #bleedingEdge (in MC repos) with these versions:

===
Name: Zinc-FileSystem-SvenVanCaekenberghe.18
Author: SvenVanCaekenberghe
Time: 27 September 2018, 2:45:54.976191 pm
UUID: a666ec74-3b33-0d00-a2f9-06800438ffe9
Ancestors: Zinc-FileSystem-SvenVanCaekenberghe.17

add ZnFileSystemUtils #readStreamFor: and #binaryReadStreamFor:
===
Name: Zinc-HTTP-SvenVanCaekenberghe.476
Author: SvenVanCaekenberghe
Time: 27 September 2018, 2:46:42.96017 pm
UUID: cc90c877-3b33-0d00-a2fa-d50c0438ffe9
Ancestors: Zinc-HTTP-SvenVanCaekenberghe.475

Fix ZnMimePart class>>#fieldName:fileNamed:
===

Sven

**Comment by ioanaverebi** [comment]
Worked like a charm! Thank you Sven!
