### ISSUE TITLE
Invalid encoding for uploaded UTF8 file streams

### ISSUE THREAD

**Issue by mtabacman** [svenvc/zinc#72]
Steps to reproduce:

1. Start with a clean Pharo 9 installation
2. Load Zinc master branch
3. Start a server in [Beeceptor](https://beeceptor.com/)
4. Create a new UTF8 text file `test.txt` in the Pharo directory, containing a single letter with diacritic (por example á)
5. Open a Playground and execute:
```
	| client |

	client := ZnClient new.

	client
		method: #POST;
		url: PATH_TO_BEECEPTOR asUrl.
	client addPart:
		( ZnMimePart fieldName: 'file' fileNamed: 'test.txt' asFileReference fullName ).

	client
		execute;
		response
```

Expected result:
The content uploaded to Beeceptor is á

Obtained result:
The content uploaded to Beeceptor is � 

This can be "fixed" by changing `ZnMimePart class>>#fieldName:fileNamed:` and sending `contents utf8Encoded readStream` to the filestream, but of course that is not ideal since it would imply forcefully loading the content and re-encoding it.

**Comment by svenvc** [comment]
Hi,

Thanks for the bug report. Indeed, something is wrong here. More specifically in the method ZnMimePart class>>#fieldName:fileNamed: as you noticed as well.

The following does work:
```
ZnClient new
	url: 'http://zn.stfx.eu/echo';
	addPart: (ZnMimePart fieldName: 'file' fileName: '/tmp/file.txt' entity: (ZnEntity with: 'á'));
	post.
```
because it uses a more primitive approach.

The problem is in the way the streaming entity is used, with respect to either a binary or textual file.

I have to think a bit more about this and will come back to you.

Sven

PS: the unit tests ZnServerTest>>testFormTest3 and ZnServerTest>>#testFormTest3Unspecified cover this, while ZnClientTest>>#testPostMultipart could probably extended with a non-ascii file to cover your issue.

**Comment by svenvc** [comment]
Hi,

The following should fix your issue: https://github.com/svenvc/zinc/commit/c2e788a5f8092cae8bcd4f8f26575c6db3664778

Can you confirm this ?

Sven

**Comment by mtabacman** [comment]
Yes! I can confirm that change fixes the issue

**Comment by svenvc** [comment]
OK, good.

Thanks again for the bug report.
