### ISSUE TITLE
ZdcSocketStream dnu #crlf and doesn't handle Characters

### ISSUE THREAD

**Issue by pdebruic** [svenvc/zinc#95]
See https://github.com/SeasideSt/Seaside/issues/1145

Would changing to `ZnChunkedWriteStream` in `ZnZincStreamingServerAdaptor>>#responseFor:` take care of that issue?

**Comment by svenvc** [comment]
In principle, Zinc uses its socket streams (classic, secure, zdc classic or secure) as binary. Some wrapping streams add some bivalent capability (to be able to write both bytes as characters), as needed (ZnBivalentWriteStream but also others). Some are a bit confusing, I admit.

Now, on itself, ZnChunkedWriteStream does not add bivalent capabilities. So that would not solve anything.

ZnZincStreamingServerAdaptor is really part of Seaside, not Zinc. I have not written it.

**Comment by pdebruic** [comment]
Ahh ok! Thanks for the note.
